### ISSUE TITLE
When rapidly refreshing only first `@src` is applied

### ISSUE THREAD

**Issue by shogun70** [gustafnk/h-include#15]
If I change `@src` and call `refresh()` twice within too short an interval then the second `@src` isn't applied. I also (often but not always) see this if the `<h-include>` in the markup has an initial `@src` and this is changed during `window.onload`.

See attached files.

[refresh.zip](https://github.com/gustafnk/h-include/files/254255/refresh.zip)

**Comment by gustafnk** [comment]
Yes, good catch. I suspect that this problem exists in the original hinclude.js as well.

**Comment by gustafnk** [comment]
Thinking out loud...

If we only supported the `async` mode, I think we could keep a map of `(request, element)` (or maybe the opposite), tracking outstanding requests against their elements. An element should only be allowed to have a single outstanding request. If an element with an outstanding request changed its @src attribute, the outstanding request should be cancelled.

However, with the `buffered` mode in the equation as well, I don't know. If the request for the element is completed and just waiting to be rendered in the buffer, it feels weird to remove it from the buffer just because the @src attribute changed.

I'll start thinking about how to move forward with the `async` mode. However, I already suspect a memory leak problem if we don't use a WeakMap polyfill like [this](https://github.com/Benvie/WeakMap), since we'll have object as keys.

**Comment by shogun70** [comment]
Just looking at the code I would guess that changing 

``` .js
 include = hinclude.buffer.pop();
```

to 

``` .js
 include = hinclude.buffer.shift();
```

in `show_buffered_content()` shoud fix this. Will test that when I can.

**Comment by shogun70** [comment]
Actually there is one more place where the buffered content can get out of order:

`set_buffered_content()` only pushes the `[element, req]` pair onto `buffer` when the download is complete. With rapid refreshes there is a chance that the second download completes before the first. (The current tests aren't likely to catch this).

I've made [an ugly hack](https://github.com/gustafnk/h-include/compare/master...shogun70:issue15) that seems to fix this.

**Comment by gustafnk** [comment]
Idea: when @src is changed:
- abort possible outstanding request (depending on its state)
- if buffered mode, find request in buffer and remove it

**Comment by gustafnk** [comment]
Since https://github.com/gustafnk/h-include/pull/60 , the support for refreshing the `h-include` on @src attribute change is removed.

If we find a way to re-enable the support, we should think about this problem as well.
