### ISSUE TITLE
document.registerElement is deprecated

### ISSUE THREAD

**Issue by pellec** [gustafnk/h-include#51]
My browser (Chrome) complains that ```document.registerElement``` is deprecated and will be removed around March 2019. 

Is there any ongoing work to use the suggested method ```window.customerElements.define``` instead?

![image](https://user-images.githubusercontent.com/1078388/48772921-21d3ab80-ecc6-11e8-8799-56076cc9795e.png)

**Comment by gustafnk** [comment]
Hi! Thanks for noticing this :)

Since the recommended polyfill [document-register-element](https://github.com/WebReflection/document-register-element) will be applied after the deprecation, Chrome users will still get Custom Elements v0 functionality and `h-include` will continue to work.

However, in the long run it's unnecessary to polyfill [browsers that supports Custom Elements v1](https://caniuse.com/#feat=custom-elementsv1), so I definitely think `h-include` should be using v1.

I'm currently have quite limited time to start working on this though :( I'd be super happy if you (or someone else) could create a PR which migrates to v1 and works in common browsers (with and without support for CE v1). And, if it works well, I could make a release during Christmas holidays perhaps.

**Comment by shogun70** [comment]
See #52

**Comment by gustafnk** [comment]
Fixed in https://github.com/gustafnk/h-include/pull/60

I'm planning to create a new version of the npm package during the next weeks.

**Comment by gustafnk** [comment]
Released 3.0.0!

https://github.com/gustafnk/h-include/releases/tag/v3.0.0
